ings_lst = [
'2 pounds lean ground beef',
 '1/3 cup finely chopped green bell pepper',
 '1/3 cup finely chopped onion',
 '2 eggs',
 '1 1/2 cups Italian-style dry bread crumbs',
 '1/2 teaspoon salt',
 '1/4 teaspoon ground black pepper',
 '2 (10.75 ounce) cans condensed golden mushroom soup',
 '1 cup sliced fresh mushrooms',
 '1 cup sour cream',
 '1/2 cup milk',
 '2 tablespoons browning sauce',
 'salt to taste',
 'ground black pepper to taste',
 '1 (10 ounce) can refrigerated biscuit dough (such as Pillsbury Grands!®)',
 '1 (1 pound) bulk pork sausage',
 '1 1/2 cups shredded Cheddar cheese, divided',
 '6 eggs',
 '1/2 cup milk',
 'salt and ground black pepper to taste',
 '1 1/2 cups cold water, or more as needed',
 '1 (1.5 ounce) package pork gravy mix',
 '2 (4 ounce) filet mignon steaks',
 '1/2 teaspoon freshly ground black pepper to taste',
 'salt to taste',
 '1/4 cup balsamic vinegar',
 '1/4 cup dry red wine',
 '2 eggs',
 '3/4 cup milk',
 '2/3 cup seasoned bread crumbs',
 '2 teaspoons dried minced onion',
 '1 teaspoon salt',
 '1/2 teaspoon rubbed sage',
 '1/2 cup sliced fresh mushrooms',
 '1 1/2 pounds ground beef',
 '1/4 cup ketchup',
 '2 tablespoons brown sugar',
 '1 teaspoon ground mustard',
 '1/2 teaspoon Worcestershire sauce',
 'cooking spray',
 '1 whole chicken, cut into 8 pieces',
 '1 teaspoon salt',
 '1 teaspoon ground black pepper',
 '1 teaspoon ground paprika',
 '1 teaspoon garlic powder',
 '1 teaspoon dried oregano',
 '1 1/2 pounds sweet potatoes, peeled and cut into 1-inch pieces',
 '1 pound chicken tenders',
 '2 teaspoons steak seasoning (such as Montreal Steak Seasoning®)',
 '2 tablespoons vegetable oil',
 '1/2 cup maple syrup',
 '1/2 cup sliced green onions',
 '1 tablespoon butter',
 '1/2 onion, chopped',
 '1/4 cup melted butter',
 '1/4 cup flour',
 '2 cups milk',
 '2 cups chicken stock',
 '1 1/2 cups coarsely chopped broccoli florets',
 '1 cup matchstick-cut carrots',
 '1 stalk celery, thinly sliced',
 '2 1/2 cups shredded sharp Cheddar cheese',
 'salt and ground black pepper to taste',
 '6 skinless, boneless chicken breast halves',
 '6 slices Swiss cheese',
 '6 slices ham',
 '3 tablespoons all-purpose flour',
 '1 teaspoon paprika',
 '6 tablespoons butter',
 '1/2 cup dry white wine',
 '1 teaspoon chicken bouillon granules',
 '1 tablespoon cornstarch',
 '1 cup heavy whipping cream',
 '1 tablespoon vegetable oil',
 '1 onion, chopped',
 '1 (10 ounce) package frozen chopped spinach, thawed and drained',
 '5 eggs, beaten',
 '3 cups shredded Muenster cheese',
 '1/4 teaspoon salt',
 '1/8 teaspoon ground black pepper',
 '2 kiwis, peeled and diced',
 '2 Golden Delicious apples - peeled, cored and diced',
 '8 ounces raspberries',
 '1 pound strawberries',
 '2 tablespoons white sugar',
 '1 tablespoon brown sugar',
 '3 tablespoons fruit preserves, any flavor',
 '10 (10 inch) flour tortillas',
 'butter flavored cooking spray',
 '2 tablespoons cinnamon sugar',
 '2 pounds ground beef chuck',
 '1 pound bulk Italian sausage',
 '3 (15 ounce) cans chili beans, drained',
 '1 (15 ounce) can chili beans in spicy sauce',
 '2 (28 ounce) cans diced tomatoes with juice',
 '1 (6 ounce) can tomato paste',
 '1 large yellow onion, chopped',
 '3 stalks celery, chopped',
 '1 green bell pepper, seeded and chopped',
 '1 red bell pepper, seeded and chopped',
 '2 green chile peppers, seeded and chopped',
 '1 tablespoon bacon bits',
 '4 cubes beef bouillon',
 '1/2 cup beer',
 '1/4 cup chili powder',
 '1 tablespoon Worcestershire sauce',
 '1 tablespoon minced garlic',
 '1 tablespoon dried oregano',
 '2 teaspoons ground cumin',
 '2 teaspoons hot pepper sauce (e.g. Tabasco™)',
 '1 teaspoon dried basil',
 '1 teaspoon salt',
 '1 teaspoon ground black pepper',
 '1 teaspoon cayenne pepper',
 '1 teaspoon paprika',
 '1 teaspoon white sugar',
 '1 (10.5 ounce) bag corn chips such as Fritos®',
 '1 (8 ounce) package shredded Cheddar cheese',
 '2 teaspoons olive oil',
 '2 slices bacon, cut into small pieces',
 '1/2 yellow onion, diced',
 '1 rib celery, diced',
 '2 cloves garlic, minced',
 '1 (8 ounce) bottle clam juice',
 '1 cup low-sodium chicken broth',
 '1 cup cubed Yukon Gold potatoes',
 '1 pinch cayenne pepper, or to taste',
 'freshly ground black pepper to taste',
 '1/2 cup heavy whipping cream',
 '1 red Fresno chile pepper, diced',
 '1 teaspoon lemon zest',
 'salt to taste',
 '1 pound bay scallops',
 '1 tablespoon chopped fresh tarragon']
