ings_lst = [
'2 pounds lean ground beef',
 '1/3 cup finely chopped green bell pepper',
 '1/3 cup finely chopped onion',
 '2 eggs',
 '1 1/2 cups Italian-style dry bread crumbs',
 '1/2 teaspoon salt',
 '1/4 teaspoon ground black pepper',
 '2 (10.75 ounce) cans condensed golden mushroom soup',
 '1 cup sliced fresh mushrooms',
 '1 cup sour cream',
 '1/2 cup milk',
 '2 tablespoons browning sauce',
 'salt to taste',
 'ground black pepper to taste',
 '1 (10 ounce) can refrigerated biscuit dough (such as Pillsbury Grands!®)',
 '1 (1 pound) bulk pork sausage',
 '1 1/2 cups shredded Cheddar cheese, divided',
 '6 eggs',
 '1/2 cup milk',
 'salt and ground black pepper to taste',
 '1 1/2 cups cold water, or more as needed',
 '1 (1.5 ounce) package pork gravy mix',
 '2 (4 ounce) filet mignon steaks',
 '1/2 teaspoon freshly ground black pepper to taste',
 'salt to taste',
 '1/4 cup balsamic vinegar',
 '1/4 cup dry red wine',
 '2 eggs',
 '3/4 cup milk',
 '2/3 cup seasoned bread crumbs',
 '2 teaspoons dried minced onion',
 '1 teaspoon salt',
 '1/2 teaspoon rubbed sage',
 '1/2 cup sliced fresh mushrooms',
 '1 1/2 pounds ground beef',
 '1/4 cup ketchup',
 '2 tablespoons brown sugar',
 '1 teaspoon ground mustard',
 '1/2 teaspoon Worcestershire sauce',
 'cooking spray',
 '1 whole chicken, cut into 8 pieces',
 '1 teaspoon salt',
 '1 teaspoon ground black pepper',
 '1 teaspoon ground paprika',
 '1 teaspoon garlic powder',
 '1 teaspoon dried oregano',
 '1 1/2 pounds sweet potatoes, peeled and cut into 1-inch pieces',
 '1 pound chicken tenders',
 '2 teaspoons steak seasoning (such as Montreal Steak Seasoning®)',
 '2 tablespoons vegetable oil',
 '1/2 cup maple syrup',
 '1/2 cup sliced green onions',
 '1 tablespoon butter',
 '1/2 onion, chopped',
 '1/4 cup melted butter',
 '1/4 cup flour',
 '2 cups milk',
 '2 cups chicken stock',
 '1 1/2 cups coarsely chopped broccoli florets',
 '1 cup matchstick-cut carrots',
 '1 stalk celery, thinly sliced',
 '2 1/2 cups shredded sharp Cheddar cheese',
 'salt and ground black pepper to taste',
 '6 skinless, boneless chicken breast halves',
 '6 slices Swiss cheese',
 '6 slices ham',
 '3 tablespoons all-purpose flour',
 '1 teaspoon paprika',
 '6 tablespoons butter',
 '1/2 cup dry white wine',
 '1 teaspoon chicken bouillon granules',
 '1 tablespoon cornstarch',
 '1 cup heavy whipping cream',
 '1 tablespoon vegetable oil',
 '1 onion, chopped',
 '1 (10 ounce) package frozen chopped spinach, thawed and drained',
 '5 eggs, beaten',
 '3 cups shredded Muenster cheese',
 '1/4 teaspoon salt',
 '1/8 teaspoon ground black pepper',
 '2 kiwis, peeled and diced',
 '2 Golden Delicious apples - peeled, cored and diced',
 '8 ounces raspberries',
 '1 pound strawberries',
 '2 tablespoons white sugar',
 '1 tablespoon brown sugar',
 '3 tablespoons fruit preserves, any flavor',
 '10 (10 inch) flour tortillas',
 'butter flavored cooking spray',
 '2 tablespoons cinnamon sugar',
 '2 pounds ground beef chuck',
 '1 pound bulk Italian sausage',
 '3 (15 ounce) cans chili beans, drained',
 '1 (15 ounce) can chili beans in spicy sauce',
 '2 (28 ounce) cans diced tomatoes with juice',
 '1 (6 ounce) can tomato paste',
 '1 large yellow onion, chopped',
 '3 stalks celery, chopped',
 '1 green bell pepper, seeded and chopped',
 '1 red bell pepper, seeded and chopped',
 '2 green chile peppers, seeded and chopped',
 '1 tablespoon bacon bits',
 '4 cubes beef bouillon',
 '1/2 cup beer',
 '1/4 cup chili powder',
 '1 tablespoon Worcestershire sauce',
 '1 tablespoon minced garlic',
 '1 tablespoon dried oregano',
 '2 teaspoons ground cumin',
 '2 teaspoons hot pepper sauce (e.g. Tabasco™)',
 '1 teaspoon dried basil',
 '1 teaspoon salt',
 '1 teaspoon ground black pepper',
 '1 teaspoon cayenne pepper',
 '1 teaspoon paprika',
 '1 teaspoon white sugar',
 '1 (10.5 ounce) bag corn chips such as Fritos®',
 '1 (8 ounce) package shredded Cheddar cheese',
 '2 teaspoons olive oil',
 '2 slices bacon, cut into small pieces',
 '1/2 yellow onion, diced',
 '1 rib celery, diced',
 '2 cloves garlic, minced',
 '1 (8 ounce) bottle clam juice',
 '1 cup low-sodium chicken broth',
 '1 cup cubed Yukon Gold potatoes',
 '1 pinch cayenne pepper, or to taste',
 'freshly ground black pepper to taste',
 '1/2 cup heavy whipping cream',
 '1 red Fresno chile pepper, diced',
 '1 teaspoon lemon zest',
 'salt to taste',
 '1 pound bay scallops',
 '1 tablespoon chopped fresh tarragon',
'2 tablespoons sesame oil',
 '2 tablespoons reduced-sodium soy sauce',
 '2 teaspoons maple syrup',
 '1 1/2 teaspoons miso paste',
 '1 teaspoon liquid smoke flavoring',
 '1/2 teaspoon ground paprika',
 '1/2 teaspoon ground black pepper',
 '2 sheets rice paper',
 '1 teaspoon vegetable oil',
 '1 onion, chopped',
 '3 cloves garlic, chopped',
 '3/4 cup quinoa',
 '1 1/2 cups vegetable broth',
 '1 teaspoon ground cumin',
 '1/4 teaspoon cayenne pepper',
 'salt and ground black pepper to taste',
 '1 cup frozen corn kernels',
 '2 (15 ounce) cans black beans, rinsed and drained',
 '1/2 cup chopped fresh cilantro',
 '1 onion, peeled and halved',
 '3 cups dry pinto beans, rinsed',
 '1/2 fresh jalapeno pepper, seeded and chopped',
 '2 tablespoons minced garlic',
 '5 teaspoons salt',
 '1 3/4 teaspoons fresh ground black pepper',
 '1/8 teaspoon ground cumin, optional',
 '9 cups water',
 '2 heads broccoli, separated into florets',
 '2 teaspoons extra-virgin olive oil',
 '1 teaspoon sea salt',
 '1/2 teaspoon ground black pepper',
 '1 clove garlic, minced',
 '1/2 teaspoon lemon juice',
 '6 tablespoons rice wine vinegar',
 '6 tablespoons vegetable oil',
 '5 tablespoons creamy peanut butter',
 '3 tablespoons soy sauce',
 '3 tablespoons brown sugar',
 '2 tablespoons minced fresh ginger root',
 '1 1/2 tablespoons minced garlic',
 '5 cups thinly sliced green cabbage',
 '2 cups thinly sliced red cabbage',
 '2 cups shredded napa cabbage',
 '2 red bell peppers, thinly sliced',
 '2 carrots, julienned',
 '6 green onions, chopped',
 '1/2 cup chopped fresh cilantro',
 '1 pound skinless, boneless chicken breast halves - cut into 1 inch cubes',
 '1 pound andouille sausage, sliced',
 '1 (28 ounce) can diced tomatoes with juice',
 '1 large onion, chopped',
 '1 large green bell pepper, chopped',
 '1 cup chopped celery',
 '1 cup chicken broth',
 '2 teaspoons dried oregano',
 '2 teaspoons dried parsley',
 '2 teaspoons Cajun seasoning',
 '1 teaspoon cayenne pepper',
 '1/2 teaspoon dried thyme',
 '1 pound frozen cooked shrimp without tails',
 '1/2 cup unsalted butter',
 '3/4 cup chopped dried sweetened pineapple',
 '1 cup all-purpose flour',
 '1 cup yellow cornmeal',
 '1/2 teaspoon baking soda',
 '1/2 teaspoon salt',
 '1 cup buttermilk',
 '2 large eggs',
 '1 cup milk',
 '1/2 cup water',
 '1/4 cup butter',
 '4 1/2 cups all-purpose flour',
 '1 (.25 ounce) package instant yeast',
 '2 tablespoons white sugar',
 '1 1/2 teaspoons salt',
 '1 egg',
 '1/4 cup white sugar',
 '1 teaspoon ground cinnamon',
 '3/4 cup butter',
 '3 cups white sugar',
 '3 eggs',
 '6 very ripe bananas, mashed',
 '1 (16 ounce) container sour cream',
 '2 teaspoons vanilla extract',
 '2 teaspoons ground cinnamon',
 '1/2 teaspoon salt',
 '3 teaspoons baking soda',
 '4 1/2 cups all-purpose flour',
 '1 cup chopped walnuts (optional)',
 '1/2 cup warm water (110 degrees F/45 degrees C)',
 '1/2 cup warm milk',
 '1 egg',
 '1/3 cup butter, softened',
 '1/3 cup white sugar',
 '1 teaspoon salt',
 '3 3/4 cups all-purpose flour',
 '1 (.25 ounce) package active dry yeast',
 '1/4 cup butter, softened',
 '4 eggs',
 '2 cups white sugar',
 '1 cup vegetable oil',
 '1 teaspoon vanilla extract',
 '4 cups all-purpose flour',
 '1 teaspoon salt',
 '1 teaspoon baking soda',
 '2 cups sour cream',
 '2 cups blueberries',
 '4 skinless, boneless chicken breast halves',
 '2 tablespoons butter',
 '2 (10.75 ounce) cans condensed cream of chicken soup',
 '1 onion, finely diced',
 '2 (10 ounce) packages refrigerated biscuit dough, torn into pieces',
 '6 skinless, boneless chicken breast halves',
 '6 slices Swiss cheese',
 '6 slices ham',
 '3 tablespoons all-purpose flour',
 '1 teaspoon paprika',
 '6 tablespoons butter',
 '1/2 cup dry white wine',
 '1 teaspoon chicken bouillon granules',
 '1 tablespoon cornstarch',
 '1 cup heavy whipping cream',
 '1 tablespoon cornstarch',
 '1 tablespoon cold water',
 '1/2 cup white sugar',
 '1/2 cup soy sauce',
 '1/4 cup cider vinegar',
 '1 clove garlic, minced',
 '1/2 teaspoon ground ginger',
 '1/4 teaspoon ground black pepper',
 '12 skinless chicken thighs',
 '2 pounds beef stew meat, cut into 1 inch cubes',
 '1 (14.5 ounce) can diced tomatoes with juice',
 '1 cup water',
 '3 tablespoons instant tapioca',
 '1 tablespoon beef bouillon granules',
 '2 teaspoons white sugar',
 '1 1/2 teaspoons salt',
 '1/4 teaspoon ground black pepper',
 '4 carrots, cut into 1 inch pieces',
 '2 strips celery, cut into 3/4 inch pieces',
 '3 potato, peeled and cubed',
 '1 onion, roughly chopped',
 '1 slice bread, cubed',
 '1 (3 pound) butternut squash - peeled, seeded, and cubed',
 '1 tablespoon olive oil',
 'salt and ground black pepper to taste',
 '8 strips bacon, chopped',
 '1 large onion, chopped',
 '6 stalks celery, chopped',
 '6 carrots, chopped',
 '1 bay leaf',
 '2 teaspoons curry powder',
 '1 teaspoon dried thyme',
 'salt and ground black pepper to taste',
 '1 Granny Smith apple - peeled, cored, and cubed',
 '4 cloves garlic, minced',
 '1 cup apple cider',
 '1 1/2 quarts chicken stock',
 '1/2 teaspoon ground nutmeg (optional)',
 '1 1/2 cups sour cream',
 '2 pounds cubed beef stew meat',
 '3 tablespoons vegetable oil',
 '4 cubes beef bouillon, crumbled',
 '4 cups water',
 '1 teaspoon dried rosemary',
 '1 teaspoon dried parsley',
 '1/2 teaspoon ground black pepper',
 '3 large potatoes, peeled and cubed',
 '4 carrots, cut into 1 inch pieces',
 '4 stalks celery, cut into 1 inch pieces',
 '1 large onion, chopped',
 '2 teaspoons cornstarch',
 '2 teaspoons cold water',
 '1 pound sweet Italian sausage, casings removed',
 '1 cup chopped onion',
 '2 cloves garlic, minced',
 '5 cups beef broth',
 '1/2 cup water',
 '1/2 cup red wine',
 '4 large tomatoes - peeled, seeded and chopped',
 '1 cup thinly sliced carrots',
 '1/2 tablespoon packed fresh basil leaves',
 '1/2 teaspoon dried oregano',
 '1 (8 ounce) can tomato sauce',
 '1 1/2 cups sliced zucchini',
 '8 ounces fresh tortellini pasta',
 '3 tablespoons chopped fresh parsley',
 '2 (3 ounce) packages ramen noodles, crushed',
 '1 cup blanched slivered almonds',
 '2 teaspoons sesame seeds',
 '1/2 cup butter, melted',
 '1 head napa cabbage, shredded',
 '1 bunch green onions, chopped',
 '3/4 cup vegetable oil',
 '1/4 cup distilled white vinegar',
 '1/2 cup white sugar',
 '2 tablespoons soy sauce']
